name: Cleanup old workflow runs

on:
  schedule:
    - cron: '0 0 * * *' # runs daily

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: actions/workflow-run-cleanup-action@v0.6.0
        with:
          retain_runs: 3